# Generated by Django 6.0.6 on 2026-07-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['start'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
