# Generated by Django 6.0.6 on 2026-07-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['start_date'], 'verbose_name': 'Objective', 'verbose_name_plural': 'Objectives'},
        ),
    ]
