# Generated by Django 6.0.6 on 2026-07-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField()),
                ('estimated_days', models.PositiveIntegerField()),
                ('extra_days', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='objectives.objective')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
