# Generated by Django 6.0.6 on 2026-07-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['order_index'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('PEDING', 'Peding'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PEDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='extra_days',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
